name: Prepare Release

on:
  push:
    branches:
      - main
      - release/v*

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: ${{ ! contains(github.head_ref, 'release-please--branches--') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Preparation
        if: ${{ ! contains(github.ref, 'release/') }}
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.ref_name }}
      - name: Pre-Release Preparation
        if: ${{ contains(github.ref, 'release/') }}
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-pre-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.ref_name }}
