name: Prepare Release

on:
  push:
    branches:
      - main
      - release/v*

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: ${{ ! contains(github.head_ref, 'release-please--branches--') }}
    runs-on: ubuntu-latest
    steps:
      - name: Outputs
        id: outputs
        run: |
          echo "ref"
          echo "${{ github.ref }}"
          echo "head_ref"
          echo "${{ github.head_ref }}"
      - name: Release Preparation
        if: ${{ ! contains(github.ref, 'release/') }}
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Pre-Release Preparation
        if: ${{ contains(github.ref, 'release/') }}
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-pre-config.json
          manifest-file: .release-please-manifest.json
